### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by fredcamps** [jamesmacfie/space-tab#12]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app.asar/src/atom.js:57:13)
Object.activate (/home/fred/.atom/packages/space-tab/lib/space-tab.coffee:3:7)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:242:19)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:223:30)
```

**Comment by jamesmacfie** [comment]
Fixed in v0.3.0. Thanks
